### ISSUE TITLE
Testing coverage

### ISSUE THREAD

**Issue by LoriBru** [jessehouwing/azure-pipelines-tasks-zips#10]
Hi, I've been using your task to build and run the unit tests of my .NET Framework 4.7 application.
Everything runs smoothly, also the code coverage.
What I do is passing this parameter to the task:
`/collect:"Code Coverage;Format=Cobertura"`

Now I am in the process of migrating the application to .NET7 and while everything works fine for the building part of the pipeline, I cannot get the coverage anymore. My test projects reference both Microsoft.CodeCoverage and coverlet.collector but the parameter is no longer recognized, and I get the following error:
`Unable to find a data collector with friendly name 'Code Coverage'`

I already did some unsuccessful tests, but before going on I wanted to check if there is any incompatibility with your task and the coverage on .NET (not Framework) projects.
Thank you.

**Comment by jessehouwing** [comment]
This is not really 'my task', but a standard task from Microsoft to which i have only changed the same so I can publish it.

It should be able to do everything the normal task can. But you may need to upgrade your agent to a more recent version.

**Comment by LoriBru** [comment]
Thanks a lot for the quick reply, I'll give it a try with an update!

**Comment by jessehouwing** [comment]
I'm guessing you may want to configure the "xplat code coverage"  provider for net 7.

**Comment by LoriBru** [comment]
I tried that indeed, but I get the same message
`Unable to find a data collector with friendly name 'XPlat Code Coverage'`

**Comment by jessehouwing** [comment]
Does it work when you try this on Azure DevOps with a similar configuration? I feel it must be an issue with the underlying task, nog my liberated version of it.
