### ISSUE TITLE
This extension is not installable on any currently installed products. (2019 DevOps)

### ISSUE THREAD

**Issue by Chrisbpy** [jessehouwing/azure-pipelines-tasks-zips#18]
When running your VSIX installer it fails to find the installed Team Foundation Server (DevOps) installation.  

Installed version is 17.153.32407.5 (AzureDevOps2019.Update1.2)

How is the installation detected?

Log file:

```
1/11/2024 10:32:13 PM - Microsoft VSIX Installer
1/11/2024 10:32:13 PM - -------------------------------------------
1/11/2024 10:32:13 PM - Initializing Install...
1/11/2024 10:32:15 PM - Extension Details...
1/11/2024 10:32:15 PM - 	Identifier      : visualstudio
1/11/2024 10:32:15 PM - 	Name            : Visual Studio 2022 for Azure DevOps Server
1/11/2024 10:32:15 PM - 	Author          : jessehouwing
1/11/2024 10:32:15 PM - 	Version         : 231.5.1
1/11/2024 10:32:15 PM - 	Description     : Adds side-by-side version of Visual Studio 2022 for Azure DevOps Server.
1/11/2024 10:32:15 PM - 	Locale          : en-US
1/11/2024 10:32:15 PM - 	MoreInfoURL     : 
1/11/2024 10:32:15 PM - 	InstalledByMSI  : False
1/11/2024 10:32:15 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/11/2024 10:32:15 PM - 
1/11/2024 10:32:15 PM - 	Supported Products : 
1/11/2024 10:32:15 PM - 		Microsoft.TeamFoundation.Server
1/11/2024 10:32:15 PM - 			Version : [16.0,19.0)
1/11/2024 10:32:15 PM - 
1/11/2024 10:32:15 PM - 	References      : 
1/11/2024 10:32:15 PM - 
1/11/2024 10:32:15 PM - Searching for applicable products...
1/11/2024 10:32:16 PM - Found installed product - Microsoft Visual Studio 2010 Ultimate
1/11/2024 10:32:16 PM - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
1/11/2024 10:32:16 PM - Found installed product - Microsoft Visual Studio Premium 2013
1/11/2024 10:32:16 PM - Found installed product - Microsoft Visual Studio Professional 2013
1/11/2024 10:32:16 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
1/11/2024 10:32:16 PM - Found installed product - Global Location
1/11/2024 10:32:16 PM - Found installed product - ssms
1/11/2024 10:32:16 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by jessehouwing** [comment]
https://learn.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops&tabs=browser

**Comment by Chrisbpy** [comment]
Hi Jesse, thanks for that, I was installing it incorrectly.  I went to https://servername:8080/tfs/_gallery/manage and went to install it from there.  
Now I get:

"Upload Error

The extension package size '38060652 bytes' exceeds the maximum package size '26214400 bytes'"

When searching this error your name comes up trying to help someone else with their extension, so not sure if you have any solutions to that.

Visual Studio 2022 will not be installed to the server but will be on a remote build agent.

**Comment by Chrisbpy** [comment]
I found a workaround for the extension package size.  The following query ran against the configuration database allowed for successful installation.

DECLARE @keyvalues dbo.typ_keyvaluepairstringtablenullable;

INSERT @keyvalues

VALUES ('#\Configuration\Service\Gallery\LargeExtensionUpload\MaxPackageSizeMB\', '30')

exec prc_UpdateRegistry 1, @keyvalues

**Comment by jessehouwing** [comment]
https://techcommunity.microsoft.com/t5/azure-devops-blog/upload-error-the-extension-package-size-26272573-bytes-exceeds/ba-p/3048916

**Comment by Chrisbpy** [comment]
2022 building successfully.  Thanks!
