### ISSUE TITLE
The  new tasks appear as duplicates

### ISSUE THREAD

**Issue by JimMcAllister** [jessehouwing/azure-pipelines-tasks-zips#2]
The task installed without issue. However, when adding build tasks for either MSBuild or Visual Studio Build to a build definition in a classic pipeline they show as being identically labeled ( see screenshots ). You just have to pick both and then see which Visual Studio versions are supported and discard the built-in one. I was expecting the description of the task to be unique based on your description.

using task version 1.202.3 on Azure DevOps Server 2020.1.1U4

![3-11-2022 3-14-43 PM](https://user-images.githubusercontent.com/56319671/157971007-b632cd22-457f-447a-900c-22881330a873.png)
![3-11-2022 3-13-32 PM](https://user-images.githubusercontent.com/56319671/157971065-95868d68-de61-4b91-a263-97593bacb728.png)
.

**Comment by jessehouwing** [comment]
You installed through the extension I assume here?

**Comment by JimMcAllister** [comment]
I installed the 1.202.3 version from downloading from the VS Marketplace. Then installed extension via Azure DevOps Gallery Extensions to the on premise server and then to the collection I was testing it on.

**Comment by jessehouwing** [comment]
Ah. Found the issue. It's caused by the fact that localized text overrides the defaults. I thought I already fixed that, but it seems it isn't.

**Comment by jessehouwing** [comment]
If you need an immediate fix, extract the vsix, and update the loc.friendlyName property if the *.resjson files.

In the mean time I'll try to find a good moment to debug this and roll out a fix.

**Comment by jessehouwing** [comment]
New build is running. You'll need to uninstall the old version from your collection and then install the new one, since the build tasks' versions remains the same, they won't be overwritten when the extension is updated in place.

**Comment by jessehouwing** [comment]
New release finished
https://github.com/jessehouwing/azure-pipelines-tasks-zips/releases/tag/m202

**Comment by JimMcAllister** [comment]
I have tried your editing suggestion and it works as you expected.

**Comment by jessehouwing** [comment]
You're very welcome! Thanks for the small fix.

If this helped you, please:

* ⭐ Star the repo
* ⭐⭐⭐⭐⭐ Leave a  review on the Azure DevOps Marketplace with a short description how these tasks helped you
  * 🛍️ [Visual Studio 2022 for Azure DevOps Server](https://marketplace.visualstudio.com/items?itemName=jessehouwing.visualstudio)
  * 🛍️ [DotNetCore 6 for Azure DevOps Server](https://marketplace.visualstudio.com/items?itemName=jessehouwing.dotnetcore)
* 💝 Consider sponsoring me or convince your employer to do so
