### ISSUE TITLE
VS2022 correctly detected but still using 2019 for some tasks

### ISSUE THREAD

**Issue by freakalot** [jessehouwing/azure-pipelines-tasks-zips#3]
Hi Jesse,

I got the VSbuild-sxs task properly working so it detects now VS2022 correctly. In the logs, I just saw, that it sill uses 2019 for calling e.g. CL.exe, Lib.exe and link.exe. 2022 is used for calling csc.exe for compiling. Not sure what went wrong here or if I have a general misunderstanding on my side, but shouldn't 2022 be used for the whole build over 2019?

```
"C:\agent\_work\_tasks\VSBuild-sxs_e611ef14-f538-5f42-8ffc-60c88f7f045c\1.199.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [17.0,18.0) -latest -format json`

`ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\CL.exe /c /I..\..\ /Zi /nologo /W3 /WX /diagnostics:column /O2 /Ob2 /Oy- /D WIN32 /D NDEBUG /D _LIB /D _MBCS /Gm- /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"x64\Release\\" /Fd"x64\Release\\vc142.pdb" /Gd /TC /FC /errorReport:queue DllMain.c Error.c Utils.c Win32.c
`

`20>CoreCompile:
         C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1616,1607,1701,1702 /fullpaths /nostdlib+ /platform:AnyCPU /errorreport:prompt /warn:4 /doc:bin\x64\Release\MiscellaneousCS.xml ...
```

Remark: We did not update the toolset for the C++-projects to v143 yet. They are still on v142.

**Comment by jessehouwing** [comment]
I don't know how C++ evaluates what SDK to use. Can you run a build in diagnostics mode and MSBuild bedbug or binary jogging turned on and share the logs?

**Comment by freakalot** [comment]
I think I figured out what happens. The C++ projects have a setting called VC++ Directories. Those have some SDK-depending Paths defined which resolve back to VS2019 which was delivering the Toolset v142. Once I update the Toolset for those projects to v143 which is delivered with VS2022, those Paths resolve to VS2022. Kind of a weird behavior for me because I don't know what happens if you don't have VS2019 installed anymore ;). Nevertheless, it looks like this is something internally in MSBuild and not caused by your pipeline task
