### ISSUE TITLE
VisualStudio 2022 missing in classic pipeline

### ISSUE THREAD

**Issue by emboss64** [jessehouwing/azure-pipelines-tasks-zips#4]
I installed the side by side VS2022 extension and the VS2022 option is missing in vstudio build task in classic pipelines:
![image](https://user-images.githubusercontent.com/110336652/185108157-8879eb40-a87b-4ecf-a918-88c80300c2be.png)

This is how the builtin version of the task looks like:
![image](https://user-images.githubusercontent.com/110336652/185108630-5194d9e0-0175-440f-8aa0-c4c40754d6df.png)

msbuild task on the other side does have the msbuild 17 option in the dropdown:
![image](https://user-images.githubusercontent.com/110336652/185108304-aa952138-cf91-46aa-aabf-67424ce7fe9a.png)

**Comment by emboss64** [comment]
My bad, just realized it's an unordered list!

**Comment by jessehouwing** [comment]
See also:

* https://github.com/PowerShell/PowerShell/issues/17404#issuecomment-1188348379
* https://stackoverflow.com/questions/73389697/keep-order-of-elements-when-parsing-json-and-writing-it-back-out
