### ISSUE TITLE
VS2022 not showing in the VsTest task

### ISSUE THREAD

**Issue by LoriBru** [jessehouwing/azure-pipelines-tasks-zips#6]
While everything works fine for the Build side-by-side task, the VsTest task does not list VS2022 in the options.
<img width="760" alt="Screenshot 2022-10-25 133216" src="https://user-images.githubusercontent.com/22811725/197763410-532b06d8-4ce7-4a90-846d-2dcfa232abcc.png">

Am I doing something wrong?
Thanks a lot for this very helpful task.

**Comment by jessehouwing** [comment]
Just pick latest. The task doesn't have an entry for 2022 on the MS repo:

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/VsTestV3/task.json#L217

**Comment by jessehouwing** [comment]
See: https://github.com/microsoft/azure-pipelines-tasks/pull/17089

**Comment by LoriBru** [comment]
Thank you, so you are saying that by picking "Latest", VS2022 will be used with the side-by-side task? Any way to confirm that when the pipeline runs?

**Comment by jessehouwing** [comment]
Yeah, you can see it here in the vstest@3 task:
https://github.com/microsoft/azure-pipelines-tasks/blob/36acb7ac81ac3bc8e93e67fe6e346adcdcffecd9/Tasks/VsTestV3/versionfinder.ts#L94

When latest is specified it first searches for 17, then 16, then 15 and older.

For some reason the dropdown item was never added, but the search code for latest was updated.

My pull request allows the explicit selection of visual studio 2022 (17.x).

**Comment by LoriBru** [comment]
It works indeed, thanks!
It is a pity I cannot make it work with the code coverage :(
